import string
import random


def generate_random_string(length: int = 12) -> str:
    """
    Generate a random string of the specified length.

    The string generated by this function will meet the following criteria:
        - First character is a letter (a-z or A-Z).
        - Subsequent characters can be letters, digits (0-9), hyphens (-), or
        underscores (_).

    Args:
        length (int, optional):
            The length of the random string to generate. Must be greater than 0.
            Defaults to 12.

    Returns:
        str: A random string of the specified length.
    """
    # validate length
    if length <= 0:
        msg = "Length must be greater than 0."
        raise ValueError(msg)

    # define possible characters
    first_characters = string.ascii_letters
    subsequent_characters = first_characters + string.digits + "-" + "_"

    # generate first character
    first_character = random.choice(first_characters)
    remaining_characters = "".join(
        random.choices(subsequent_characters, k=length - 1)
    )
    random_string = first_character + remaining_characters

    return random_string
